version: "3.7"
networks:
  mynetwork:
services:
  app:
    container_name: containerize_app_1
    build: ./app
    ports: 
      - 8000:8000

    # your code goes here ...
  nginx:
    container_name: containerize_nginx_1
    build: ./nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/files:/etc/ssl/
    depends_on:
      - app
  
  
  
  
    # your code goes here ...
