version: "3.7"
networks:
  mynetwork:
services:
  app:
    container_name: containerize_app_1
    build: ./app
    expose: 
      - 8000

    # your code goes here ...
  nginx:
    container_name: containerize_nginx_1
    build: ./nginx
    ports:
      - 80:80
      - 443:443

    # your code goes here ...
